apiVersion: apps/v1
kind: Deployment
metadata:
  name: filtermodel-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filtermodel-service
  template:
    metadata:
      labels:
        app: filtermodel-service
    spec:
      containers:
      - name: filtermodel-service
        image: <ACR_NAME>.azurecr.io/filtermodel-service:dev
        env:
        - name: DB_PROXY_HOST
          value: db-proxy
        - name: DB_PROXY_PORT
          value: "5000"
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: filtermodel-service
  namespace: dev
spec:
  selector:
    app: filtermodel-service
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
